"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Sankes_with_Shubham.py']
DATA_FILES = ['gameover.mp3','highscore.txt','snakecharmerpoc.mp3','back.jpg']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
